terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox",
      version = "2.9.14"
    }
  }
}

variable "token_id" {
  sensitive   = true
  description = "API Token ID as set in Proxmox"
  type        = string
}

variable "token_secret_value" {
  sensitive   = true
  description = "API Secret value as generated by Proxmox"
  type        = string
}

provider "proxmox" {
  pm_api_url          = "https://192.168.1.160:8006/api2/json"
  pm_api_token_id     = var.token_id
  pm_api_token_secret = var.token_secret_value
  pm_tls_insecure     = true
}

resource "proxmox-lxc" "test-alpine" {

}
