terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox",
      version = "2.9.14"
    }
  }
}

variable "ssh_public_key" {
  type        = string
  description = "Public SSH key from Yubikey"
  default     = "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILRsXI5a6WLD6eflNESoq41hjyrsn6ySCe6qKD2m1CvyAAAABHNzaDo= fester@maccie.lan"
}

variable "token_id" {
  sensitive   = true
  description = "API Token ID as set in Proxmox"
  type        = string
}

variable "token_secret_value" {
  sensitive   = true
  description = "API Secret value as generated by Proxmox"
  type        = string
}

provider "proxmox" {
  pm_api_url          = "https://192.168.1.160:8006/api2/json"
  pm_api_token_id     = var.token_id
  pm_api_token_secret = var.token_secret_value
  pm_log_enable       = true
  pm_tls_insecure     = true
  pm_debug            = true
}

resource "proxmox_lxc" "k3s-server-0" {
  # Meta info
  target_node = "kryten"
  hostname    = "k3s-server-0"
  pool        = "K3s"
  description = "K3s server node that runs the control plane and etcd."

  # OS Config
  ostemplate      = "local:vztmpl/nixos-system-x86_64-linux.tar.xz"
  unprivileged    = true
  password        = "testtest" # Does not work with NixOS
  ssh_public_keys = var.ssh_public_key
  cmode           = "console"

  # Start after creation
  start = true

  # Resource allocation
  cores  = 2    # Recommended by K3s
  memory = 1024 # in MB

  features {
    nesting = true # Allows for running containers
  }

  rootfs {
    storage = "local-lvm"
    size    = "8G"
  }

  network {
    name   = "eth0"
    bridge = "vmbr0"
    ip     = "192.168.1.220/24"
    gw     = "192.168.1.1"
  }
}
