terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox",
      version = "2.9.14"
    }
  }
}

variable "ssh_public_key" {
  type        = string
  description = "Public SSH key from Yubikey"
  default     = file("~/.ssh/id_ed25519_sk.pub")
}

variable "token_id" {
  sensitive   = true
  description = "API Token ID as set in Proxmox"
  type        = string
}

variable "token_secret_value" {
  sensitive   = true
  description = "API Secret value as generated by Proxmox"
  type        = string
}

provider "proxmox" {
  pm_api_url          = "https://192.168.1.160:8006/api2/json"
  pm_api_token_id     = var.token_id
  pm_api_token_secret = var.token_secret_value
  pm_log_enable       = true
  pm_tls_insecure     = true
  pm_debug            = true
}

resource "proxmox_lxc" "test-alpine" {
  # Meta info
  target_node = "kryten"
  hostname    = "test-alpine"
  pool        = "K3s"
  description = "Server node for K3s"

  # OS Config
  ostemplate      = "local:vztmpl/alpine-3.18-default_20230607_amd64.tar.xz"
  unprivileged    = true
  password        = "testtest"
  ssh_public_keys = <<-EOT
    ssh-ed25519-sk ${ssh_public_key} me@festerherenius.nl
  EOT

  # Resource allocation
  cores  = 2    # Recommended by K3s
  memory = 1024 # in MB

  features {
    nesting = true # Allows for running containers
  }

  rootfs {
    storage = "local-lvm"
    size    = "8G"
  }

  network {
    name   = "eth0"
    bridge = "vmbr0"
    ip     = "dhcp"
  }
}
